games = 2
survivorGames = 5
verbose = False
digits = 2
amateur = 118
goodRatio = 2.5
excludeDefensive= True
teamAmount = 495
displayThreshhold = 0.5
killThreshhold = 0.5
phases = 100
singleTeam = False
singleTeamGames = 100
pointSystem = True
